### ISSUE TITLE
精度为市区的等值线图

### ISSUE THREAD

**Issue by Log1cStudy** [huangynj/NCL-Chinamap#1]
您好，请问如何制作市区级的等值线图，例如深圳市。我看官网上一般是只到省份

**Comment by huangynj** [comment]
可以看看这里面是否有需要的市区级边界
[https://github.com/huangynj/NCL-Chinamap/blob/master/cnmap_NetCDF/county_2004.nc ](https://github.com/huangynj/NCL-Chinamap/blob/master/cnmap_NetCDF/county_2004.nc )

**Comment by Log1cStudy** [comment]
如果是制作类似于示例图：北京市等值线图；要往（Earth..4.lines、Earth..4.names）这两个文件添加指定市区的数据；我想请教一下这两个文件是如何制作的

**Comment by huangynj** [comment]
> 如果是制作类似于示例图：北京市等值线图；要往（Earth..4.lines、Earth..4.names）这两个文件添加指定市区的数据；我想请教一下这两个文件是如何制作的

如果要往 Earth..4.lines 和 Earth..4.names 添加新的边界，工作量估计有点大，得知道边界的左右区域，方向，还得找到原来数据中的连接点，两文件里面的含义可以从 NCL 源程序包的相关代码找到；我主要是修改了原有的边界和添加一些跟原数据没有太大关系的岛屿和国界，稍微简单点，但也花了不少时间。所以如果不是非必需，不建议这么做，折中办法就是用添加 shapefile 的方式。

**Comment by Log1cStudy** [comment]
请问如果是采用shapefile的方式能做到只填色某个市（Earth..4数据集的MapPlot 数据库表上没有该区域名）吗？效果图类似于您制作的北京市气压等值线图

**Comment by huangynj** [comment]
> 请问如果是采用shapefile的方式能做到只填色某个市（Earth..4数据集的MapPlot 数据库表上没有该区域名）吗？效果图类似于您制作的北京市气压等值线图

可以参考官方的例子 #21: https://www.ncl.ucar.edu/Applications/shapefiles.shtml#ex21
